# Developed by - Vedavyas Vayalpadu - vyas4c3@gmail.com
# Coded by - Claude Code
"""Derive an ADDA architecture skeleton from a codebase (spec §6.5 item 3).

A *skeleton generator*, not a full-doc writer: it lists modules (top-level source
directories, with their repo paths) and dependencies (from pyproject.toml or
package.json) so the architecture docs can be refreshed instead of rotting. The
output is a markdown skeleton the user reconciles into ARCHITECTURE.md.

`discover_modules` is shared with `adda diff`.
"""

import json
import re
from pathlib import Path

# Directories that are never project "modules" (build/tooling/test/doc noise).
IGNORE_DIRS = {
    ".git", ".venv", "venv", "env", "node_modules", "__pycache__", "dist", "build",
    ".pytest_cache", ".mypy_cache", ".ruff_cache", ".idea", ".vscode", ".github",
    "site-packages", "tests", "test", "docs", "doc", "scripts", "examples",
}


def _is_ignored(name: str) -> bool:
    return name in IGNORE_DIRS or name.startswith(".") or name.endswith(".egg-info")


def discover_modules(repo: Path) -> list[tuple[str, str]]:
    """(name, repo-relative posix path) for top-level source dirs.

    Prefers a `src/` layout when present; a dir counts only if it contains files.
    A root-level `adda/` is the scaffolded data dir (not a source module) and is
    skipped — but a `src/adda` package is kept.
    """
    base = repo / "src" if (repo / "src").is_dir() else repo
    modules = []
    for child in sorted(base.iterdir()):
        if not child.is_dir() or _is_ignored(child.name):
            continue
        if base == repo and child.name == "adda":  # the scaffolded /adda data dir
            continue
        # counts only if it holds a real file (not just noise in ignored subdirs)
        if any(
            p.is_file() and not any(_is_ignored(part) for part in p.relative_to(child).parts)
            for p in child.rglob("*")
        ):
            modules.append((child.name, child.relative_to(repo).as_posix()))
    return modules


def _dep_name(spec: str) -> str:
    """'typer>=0.12' / 'httpx[http2]>=0.24' -> 'typer' / 'httpx'."""
    return re.split(r"[<>=!~\[ ;]", spec, maxsplit=1)[0].strip()


def discover_deps(repo: Path) -> list[str]:
    """Top-level dependency names from pyproject.toml or package.json (best effort)."""
    pyproject = repo / "pyproject.toml"
    if pyproject.is_file():
        try:
            try:
                import tomllib  # py3.11+
            except ModuleNotFoundError:  # pragma: no cover - py<3.11 path
                import tomli as tomllib
            data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
            deps = (data.get("project") or {}).get("dependencies") or []
            return [_dep_name(d) for d in deps]
        except Exception:
            pass  # no toml reader / malformed -> fall through
    package = repo / "package.json"
    if package.is_file():
        try:
            data = json.loads(package.read_text(encoding="utf-8"))
            return sorted((data.get("dependencies") or {}).keys())
        except Exception:
            pass
    return []


def skeleton_markdown(repo: Path) -> str:
    """Render the derived skeleton as ARCHITECTURE-style markdown."""
    modules = discover_modules(repo)
    deps = discover_deps(repo)

    lines = [
        "<!-- Generated by `adda sync` - reconcile into your /adda/ARCHITECTURE.md. -->",
        "",
        "# Architecture (generated)",
        "",
        "## Constraints",
        "<!-- Add hard rules here; `adda sync` does not invent them. -->",
        "",
        "## Modules",
    ]
    if modules:
        lines += [f"- {name} (active) [{path}]" for name, path in modules]
    else:
        lines.append("<!-- no source modules detected -->")
    if deps:
        lines += ["", "## Dependencies (detected)"]
        lines += [f"- {d}" for d in deps]
    return "\n".join(lines)


# Files that are code paths but carry no documentable behaviour.
MAP_EXEMPT_NAMES = {"__init__.py", "__main__.py"}

# Languages whose files count as documentable code paths (ENH-ADDA-016).
# `discover_deps` already read package.json; the map generator did not, so doc
# enforcement stopped at Python while most agent-heavy codebases are TS/JS.
SOURCE_SUFFIXES = (".py", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs")


def _is_source(name: str) -> bool:
    """A documentable source file, as opposed to a declaration, test or bundle."""
    if not name.endswith(SOURCE_SUFFIXES):
        return False
    # `.d.ts` declares types for code documented elsewhere; `.min.js` is a build
    # artefact; `.test.` / `.spec.` files are tests, and `tests/` is already
    # ignored for the same reason.
    if any(b in name for b in (".d.ts", ".min.js", ".test.", ".spec.")):
        return False
    # Some ecosystems name the test file itself `test.ts` beside the module it
    # covers rather than infixing. date-fns does this 253 times; without the
    # stem check, 17% of its map demanded docs for test files.
    return name.split(".")[0] not in ("test", "tests", "spec", "specs")

# Directories that hold data, not documentable code paths. Map-local on
# purpose: IGNORE_DIRS is shared with `adda diff`, so widening it there would
# silently drop a real `templates/` source package from drift detection in
# every repo ADDA runs against.
# Third-party code vendored into the tree is not yours to document. Django
# ships 62 files of jQuery and select2 locales under static/admin/js/vendor;
# without this the map demands a module doc for jQuery (ENH-ADDA-016).
MAP_IGNORE_DIRS = IGNORE_DIRS | {"templates", "vendor", "vendored", "third_party", "third-party"}


def _map_ignored(name: str) -> bool:
    return name in MAP_IGNORE_DIRS or name.startswith(".") or name.endswith(".egg-info")


def module_map_json(repo: Path, doc_dir: str = "docs/modules") -> str:
    """Derive MODULE_MAP.json content: every source .py -> its module doc.

    The doc path MIRRORS the source path (minus a leading `src/`), so
    `src/payments/utils.py` routes to `docs/modules/payments/utils.md`.

    It used to use only the filename stem, which meant `src/payments/utils.py`
    and `src/users/utils.py` both routed to `docs/modules/utils.md` — one doc
    silently satisfying two different modules, so `audit` reported "no doc
    drift" over a module that had none (BUG-ADDA-011). Mirroring makes that
    impossible by construction: distinct source paths cannot collide.

    Reuses `discover_modules` so "what counts as source" has exactly one
    definition across sync, diff and audit.
    """
    mapping, exempt = {}, []
    candidates = discover_modules(repo)
    # Prefer real Python packages when the repo has any. FastAPI's docs_src/
    # holds 369 tutorial snippets and no __init__.py, against 41 files in the
    # fastapi/ package itself - without this, 90% of the generated map demands
    # module docs for documentation examples. Scoped to the GENERATOR:
    # discover_modules is shared with `adda diff`, and widening shared
    # behaviour for a local convenience already caused one regression.
    packaged = [c for c in candidates if (repo / c[1] / "__init__.py").is_file()]
    if packaged:
        candidates = packaged
    for _name, mod_path in candidates:
        for py in sorted(f for f in (repo / mod_path).rglob("*") if f.is_file() and _is_source(f.name)):
            rel = py.relative_to(repo).as_posix()
            # rglob descends into ignored subtrees (templates/, __pycache__/) too.
            if any(_map_ignored(part) for part in py.relative_to(repo).parts[:-1]):
                continue
            if py.name in MAP_EXEMPT_NAMES:
                exempt.append(rel)
                continue
            # mirror the path, not just the stem - see the docstring
            stem_path = rel[4:] if rel.startswith("src/") else rel
            mapping[rel] = f"{doc_dir}/{stem_path.rsplit('.', 1)[0]}.md"
    return json.dumps({"map": mapping, "exempt": sorted(exempt)}, indent=2)
