# Developed by - Vedavyas Vayalpadu - vyas4c3@gmail.com
# Coded by - Claude Code
"""Derive an ADDA architecture skeleton from a codebase (spec §6.5 item 3).

A *skeleton generator*, not a full-doc writer: it lists modules (top-level source
directories, with their repo paths) and dependencies (from pyproject.toml or
package.json) so the architecture docs can be refreshed instead of rotting. The
output is a markdown skeleton the user reconciles into ARCHITECTURE.md.

`discover_modules` is shared with `adda diff`.
"""

import json
import re
from pathlib import Path

# Directories that are never project "modules" (build/tooling/test/doc noise).
IGNORE_DIRS = {
    ".git", ".venv", "venv", "env", "node_modules", "__pycache__", "dist", "build",
    ".pytest_cache", ".mypy_cache", ".ruff_cache", ".idea", ".vscode", ".github",
    "site-packages", "tests", "test", "docs", "doc", "scripts", "examples",
}


def _is_ignored(name: str) -> bool:
    return name in IGNORE_DIRS or name.startswith(".") or name.endswith(".egg-info")


def discover_modules(repo: Path) -> list[tuple[str, str]]:
    """(name, repo-relative posix path) for top-level source dirs.

    Prefers a `src/` layout when present; a dir counts only if it contains files.
    A root-level `adda/` is the scaffolded data dir (not a source module) and is
    skipped — but a `src/adda` package is kept.
    """
    base = repo / "src" if (repo / "src").is_dir() else repo
    modules = []
    for child in sorted(base.iterdir()):
        if not child.is_dir() or _is_ignored(child.name):
            continue
        if base == repo and child.name == "adda":  # the scaffolded /adda data dir
            continue
        # counts only if it holds a real file (not just noise in ignored subdirs)
        if any(
            p.is_file() and not any(_is_ignored(part) for part in p.relative_to(child).parts)
            for p in child.rglob("*")
        ):
            modules.append((child.name, child.relative_to(repo).as_posix()))
    return modules


def _dep_name(spec: str) -> str:
    """'typer>=0.12' / 'httpx[http2]>=0.24' -> 'typer' / 'httpx'."""
    return re.split(r"[<>=!~\[ ;]", spec, maxsplit=1)[0].strip()


def discover_deps(repo: Path) -> list[str]:
    """Top-level dependency names from pyproject.toml or package.json (best effort)."""
    pyproject = repo / "pyproject.toml"
    if pyproject.is_file():
        try:
            try:
                import tomllib  # py3.11+
            except ModuleNotFoundError:  # pragma: no cover - py<3.11 path
                import tomli as tomllib
            data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
            deps = (data.get("project") or {}).get("dependencies") or []
            return [_dep_name(d) for d in deps]
        except Exception:
            pass  # no toml reader / malformed -> fall through
    package = repo / "package.json"
    if package.is_file():
        try:
            data = json.loads(package.read_text(encoding="utf-8"))
            return sorted((data.get("dependencies") or {}).keys())
        except Exception:
            pass
    return []


def skeleton_markdown(repo: Path) -> str:
    """Render the derived skeleton as ARCHITECTURE-style markdown."""
    modules = discover_modules(repo)
    deps = discover_deps(repo)

    lines = [
        "<!-- Generated by `adda sync` - reconcile into your /adda/ARCHITECTURE.md. -->",
        "",
        "# Architecture (generated)",
        "",
        "## Constraints",
        "<!-- Add hard rules here; `adda sync` does not invent them. -->",
        "",
        "## Modules",
    ]
    if modules:
        lines += [f"- {name} (active) [{path}]" for name, path in modules]
    else:
        lines.append("<!-- no source modules detected -->")
    if deps:
        lines += ["", "## Dependencies (detected)"]
        lines += [f"- {d}" for d in deps]
    return "\n".join(lines)


# Files that are code paths but carry no documentable behaviour.
MAP_EXEMPT_NAMES = {"__init__.py", "__main__.py"}

# Directories that hold data, not documentable code paths. Map-local on
# purpose: IGNORE_DIRS is shared with `adda diff`, so widening it there would
# silently drop a real `templates/` source package from drift detection in
# every repo ADDA runs against.
MAP_IGNORE_DIRS = IGNORE_DIRS | {"templates"}


def _map_ignored(name: str) -> bool:
    return name in MAP_IGNORE_DIRS or name.startswith(".") or name.endswith(".egg-info")


def module_map_json(repo: Path, doc_dir: str = "docs/modules") -> str:
    """Derive MODULE_MAP.json content: every source .py -> its module doc.

    Reuses `discover_modules` so "what counts as source" has exactly one
    definition across sync, diff and audit.
    """
    mapping, exempt = {}, []
    for _name, mod_path in discover_modules(repo):
        for py in sorted((repo / mod_path).rglob("*.py")):
            rel = py.relative_to(repo).as_posix()
            # rglob descends into ignored subtrees (templates/, __pycache__/) too.
            if any(_map_ignored(part) for part in py.relative_to(repo).parts[:-1]):
                continue
            if py.name in MAP_EXEMPT_NAMES:
                exempt.append(rel)
                continue
            mapping[rel] = f"{doc_dir}/{py.stem}.md"
    return json.dumps({"map": mapping, "exempt": sorted(exempt)}, indent=2)
